name: GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: |
        git config --global user.email "aenkun@gmail.com"
        git config --global user.name "pco2699"

    - run: npm run deploy
      env:
        PA_TOKEN: ${{ secrets.PA_TOKEN }}
        CI: true